        @php 
        $active_link = "flex items-center gap-3 rounded-xl border border-homy-gold-200 bg-homy-gold-50 px-3 py-2 text-homy-green-700 dark:border-homy-gold-600/35 dark:bg-homy-green-700/35 dark:text-homy-gold-300";
        $inactive_link = "flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25";
        @endphp
        

          <div class="mb-5 flex items-center justify-between"><h2 class="text-sm font-black text-homy-green-700 dark:text-homy-gold-400"><span class="lang-ar">قائمة الإدارة العليا</span><span class="lang-en">Super Admin Menu</span></h2><button id="closeSidebar" class="h-9 w-9 rounded-xl border border-homy-gold-200 text-homy-green-700 lg:hidden dark:border-homy-gold-600/35 dark:text-homy-gold-300"><i class="fa-solid fa-xmark"></i></button></div>
            <nav class="space-y-1.5 text-sm font-bold">
                <a href="{{ route('admin.dashboard') }}" class="{{ $inactive_link }} {{ request()->routeIs('admin.dashboard') ? $active_link : $inactive_link }}"><i class="fa-solid fa-grid-2"></i><span class="lang-ar">الرئيسية</span><span class="lang-en">Dashboard</span></a>
                <a href="{{ route('admin.join_request') }}" class="{{ $inactive_link }} {{ request()->routeIs('admin.join_request') ? $active_link : $inactive_link }}"><i class="fa-solid fa-user-plus"></i><span class="lang-ar">طلبات الانضمام</span><span class="lang-en">Vendor Applications</span></a>
                <a href="{{ route('admin.show_site_analytics') }}" class="{{ $inactive_link }} {{ request()->routeIs('admin.show_site_analytics') ? $active_link : $inactive_link }}"><i class="fa-solid fa-chart-line"></i><span class="lang-ar">إحصائيات الموقع</span><span class="lang-en">Site Analytics</span></a>
                <a href="{{ route('admin.show_product_types') }}" class="{{ $inactive_link }} {{ request()->routeIs('admin.show_product_types') ? $active_link : $inactive_link }}"><i class="fa-solid fa-layer-group"></i><span class="lang-ar">أنواع المنتجات</span><span class="lang-en">Product Types</span></a>
                <a href="{{ route('admin.show_payment_methods') }}" class="{{ $inactive_link }} {{ request()->routeIs('admin.show_payment_methods') ? $active_link : $inactive_link }}"><i class="fa-solid fa-credit-card"></i><span class="lang-ar">وسائل الدفع</span><span class="lang-en">Payment Methods</span></a>
                <a href="{{ route('admin.show_sellers_control') }}" class="{{ $inactive_link }} {{ request()->routeIs('admin.show_sellers_control') ? $active_link : $inactive_link }}"><i class="fa-solid fa-users-gear"></i><span class="lang-ar">تفاصيل البائعين</span><span class="lang-en">Sellers Details</span></a>
                <a href="{{ route('admin.show_notifications') }}" class="{{ $inactive_link }} {{ request()->routeIs('admin.show_notifications') ? $active_link : $inactive_link }}"><i class="fa-solid fa-bell"></i><span class="lang-ar">مركز الإشعارات</span><span class="lang-en">Notifications Center</span></a>
                {{-- <a href="stores-control.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-store-slash"></i><span class="lang-ar">التحكم بالمتاجر</span><span class="lang-en">Stores Control</span></a> 
                <a href="orders-control.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-truck"></i><span class="lang-ar">الطلبات</span><span class="lang-en">Orders</span></a>
                <a href="users-control.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-user-group"></i><span class="lang-ar">المستخدمون</span><span class="lang-en">Users</span></a>
                <a href="payouts.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-money-bill-transfer"></i><span class="lang-ar">السحوبات</span><span class="lang-en">Payouts</span></a>
                <a href="disputes.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-scale-balanced"></i><span class="lang-ar">النزاعات</span><span class="lang-en">Disputes</span></a>
                <a href="coupons.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-ticket"></i><span class="lang-ar">الكوبونات</span><span class="lang-en">Coupons</span></a>
                <a href="content-management.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-newspaper"></i><span class="lang-ar">إدارة المحتوى</span><span class="lang-en">Content</span></a>
                <a href="roles-permissions.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-user-shield"></i><span class="lang-ar">الأدوار والصلاحيات</span><span class="lang-en">Roles & Permissions</span></a>
                <a href="audit-logs.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-clock-rotate-left"></i><span class="lang-ar">سجل العمليات</span><span class="lang-en">Audit Logs</span></a>
                <a href="system-settings.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-sliders"></i><span class="lang-ar">إعدادات النظام</span><span class="lang-en">System Settings</span></a>
                <a href="profile-settings.html" class="flex items-center gap-3 rounded-xl px-3 py-2 text-slate-600 hover:bg-homy-gold-50 dark:text-slate-300 dark:hover:bg-homy-green-700/25"><i class="fa-solid fa-id-badge"></i><span class="lang-ar">إعدادات البروفايل</span><span class="lang-en">Profile Settings</span></a> --}}
            </nav>
